version links

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -205,19 +205,14 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer 
 sed -i "s|\$ftlUrl =.*$|\$ftlUrl = 'https:\/\/aur.archlinux.org\/packages\/pi-hole-ftl';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi
 
-#sed -i "s|\$coreReleasesUrl . \"/\" . \$core_current;|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 4" && exit 1 ; fi
-#sed -i "s|\$webReleasesUrl . \"/\" . \$web_current;|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 5" && exit 1 ; fi
-#sed -i "s|\$ftlReleasesUrl . \"/\" . \$FTL_current;|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 6" && exit 1 ; fi
-
-#sed -i "s|\$coreReleasesUrl . \"/latest\";|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 7" && exit 1 ; fi
-#sed -i "s|\$webReleasesUrl . \"/latest\";|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 8" && exit 1 ; fi
-#sed -i "s|\$ftlReleasesUrl . \"/latest\";|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 9" && exit 1 ; fi
+sed -i "s|\$core_current =.*$|\$core_current = '';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 4" && exit 1 ; fi
+sed -i "s|\$web_current =.*$|\$web_current = '';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 5" && exit 1 ; fi
+sed -i "s|\$FTL_current =.*$|\$FTL_current = '';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 6" && exit 1 ; fi
+sed -i "s|\$docker_current =.*$|\$docker_current = '';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 7" && exit 1 ; fi
 
 # -----------------
 
