core v. 5.14.1 - web v. 5.17

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-_pkgver=5.13
-_wwwpkgver=5.16
+_pkgver=5.14.1
+_wwwpkgver=5.17
 source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
 source_admin="https://github.com/pi-hole/AdminLTE/archive/v$_wwwpkgver.tar.gz"
 dircorea="pi-hole-$_pkgver"
@@ -26,15 +26,15 @@ cp -a $diradmina $diradminb
 # ================
 # version.sh patch
 # ================
-cp -a version.patch version-${_pkgver}.patch
-sed -i "s|{{_pkgver}}|v${_pkgver}|w $_ssc" ./version-${_pkgver}.patch
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 1" && exit 1 ; fi
-sed -i "s|{{_wwwpkgver}}|v${_wwwpkgver}|w $_ssc" ./version-${_pkgver}.patch
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 2" && exit 1 ; fi
-cd "$dircoreb"
-patch -p1 -i ../version-${_pkgver}.patch
-cd ..
-rm version-${_pkgver}.patch
+#cp -a version.patch version-${_pkgver}.patch
+#sed -i "s|{{_pkgver}}|v${_pkgver}|w $_ssc" ./version-${_pkgver}.patch
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 1" && exit 1 ; fi
+#sed -i "s|{{_wwwpkgver}}|v${_wwwpkgver}|w $_ssc" ./version-${_pkgver}.patch
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 2" && exit 1 ; fi
+#cd "$dircoreb"
+#patch -p1 -i ../version-${_pkgver}.patch
+#cd ..
+#rm version-${_pkgver}.patch
 # ================
 # version.sh patch
 # ================
