core v. 5.12 - web v. 5.14.2

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -198,37 +198,37 @@ sed -i 's/\$FTL_current =.*$/\$FTL_current = exec("pihole-FTL version");/' "$dir
 # -----------------
 
 # web admin footer update setup
-sed -i "s|\$coreUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+sed -i "s|\$coreUrl =.*$|\$coreUrl = 'https:\/\/aur.archlinux.org\/packages\/pi-hole-server';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 1" && exit 1 ; fi
-sed -i "s|\$webUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+sed -i "s|\$webUrl =.*$|\$webUrl = 'https:\/\/aur.archlinux.org\/packages\/pi-hole-server';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 2" && exit 1 ; fi
-sed -i "s|\$ftlUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-ftl\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
+sed -i "s|\$ftlUrl =.*$|\$ftlUrl = 'https:\/\/aur.archlinux.org\/packages\/pi-hole-ftl';|w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi
 
-sed -i "s|\$coreReleasesUrl . \"/\" . \$core_current;|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 4" && exit 1 ; fi
-sed -i "s|\$webReleasesUrl . \"/\" . \$web_current;|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 5" && exit 1 ; fi
-sed -i "s|\$ftlReleasesUrl . \"/\" . \$FTL_current;|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 6" && exit 1 ; fi
+#sed -i "s|\$coreReleasesUrl . \"/\" . \$core_current;|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 4" && exit 1 ; fi
+#sed -i "s|\$webReleasesUrl . \"/\" . \$web_current;|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 5" && exit 1 ; fi
+#sed -i "s|\$ftlReleasesUrl . \"/\" . \$FTL_current;|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 6" && exit 1 ; fi
 
-sed -i "s|\$coreReleasesUrl . \"/latest\";|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 7" && exit 1 ; fi
-sed -i "s|\$webReleasesUrl . \"/latest\";|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 8" && exit 1 ; fi
-sed -i "s|\$ftlReleasesUrl . \"/latest\";|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 9" && exit 1 ; fi
+#sed -i "s|\$coreReleasesUrl . \"/latest\";|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 7" && exit 1 ; fi
+#sed -i "s|\$webReleasesUrl . \"/latest\";|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 8" && exit 1 ; fi
+#sed -i "s|\$ftlReleasesUrl . \"/latest\";|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 9" && exit 1 ; fi
 
 # -----------------
 
 # sudo pihole full path (php-fpm compatibility)
-sed -i "s|\"sudo pihole \"|\"sudo /usr/bin/pihole \"|w $_ssc" "$diradminb"/scripts/pi-hole/php/func.php
+sed -i "s|'sudo pihole '|'sudo /usr/bin/pihole '|w $_ssc" "$diradminb"/scripts/pi-hole/php/func.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 1" && exit 1 ; fi
-sed -i "s|\"sudo pihole|\"sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
+sed -i "s|'sudo pihole|'sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 2" && exit 1 ; fi
 sed -i "s|'sudo pihole|'sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
-sed -i "s|\"sudo pihole|\"sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
+sed -i "s|'sudo pihole|'sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi
 
 # -----------------
