core and admin ver. 5.0

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-_pkgver=4.4
-_wwwpkgver=4.3.3
+_pkgver=5.0
+_wwwpkgver=5.0
 source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
 source_admin="https://github.com/pi-hole/AdminLTE/archive/v$_wwwpkgver.tar.gz"
 dircorea="pi-hole-$_pkgver"
@@ -86,12 +86,13 @@ sed -n "/uninstall/w $_ssc" "$dircoreb"/pihole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
 sed -i '/uninstall/d' "$dircoreb"/pihole
 
-sed -i "s|^  checkout.*$|\";|w $_ssc" "$dircoreb"/pihole
+sed -n "/^  checkout/w $_ssc" "$dircoreb"/pihole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi
+sed -i '/^  checkout/,+1d' "$dircoreb"/pihole
 
-sed -n "/checkout/w $_ssc" "$dircoreb"/pihole
+sed -n "/^  \"checkout/w $_ssc" "$dircoreb"/pihole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
-sed -i '/checkout/d' "$dircoreb"/pihole
+sed -i '/^  \"checkout/d' "$dircoreb"/pihole
 
 sed -n "/tricorder/w $_ssc" "$dircoreb"/pihole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
@@ -224,7 +225,7 @@ sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
 sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/sub.php
+sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/groups.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 5" && exit 1 ; fi
 sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/add.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 6" && exit 1 ; fi
@@ -232,6 +233,10 @@ sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 7" && exit 1 ; fi
 sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/loginpage.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 8" && exit 1 ; fi
+sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/teleporter.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 9" && exit 1 ; fi
+sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/customdns.php
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 9" && exit 1 ; fi
 
 # -----------------
 
@@ -246,10 +251,8 @@ echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$dircoreb"/advanced/dnsmasq.conf.orig
 cat <<EOF > "$dircoreb"/adlists.list
 https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
 https://mirror1.malwaredomains.com/files/justdomains
-http://sysctl.org/cameleon/hosts
 https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
 https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
-https://hosts-file.net/ad_servers.txt
 EOF
 
 cat <<EOF > "$dircoreb"/dns-servers.conf
