ver. 5.1web 5.1.1core

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-_pkgver=5.0
-_wwwpkgver=5.0
+_pkgver=5.1.1
+_wwwpkgver=5.1
 source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
 source_admin="https://github.com/pi-hole/AdminLTE/archive/v$_wwwpkgver.tar.gz"
 dircorea="pi-hole-$_pkgver"
@@ -114,8 +114,8 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 1" &
 
 # -----------------
 
-# setting up and securing webpage.sh script
-sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+# setting up and securing pihole-reenable.sh script
+sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/pihole-reenable.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && exit 1 ; fi
 
 # -----------------
@@ -144,8 +144,8 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bi
 # -----------------
 
 # change FTL port file location to chronometer.sh
-sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$dircoreb"/advanced/Scripts/chronometer.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change FTL port file location to chronometer.sh" && exit 1 ; fi
+#sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$dircoreb"/advanced/Scripts/chronometer.sh
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change FTL port file location to chronometer.sh" && exit 1 ; fi
 
 # -----------------
 
@@ -160,8 +160,8 @@ sed -i '/\-\- Generate debug log \-\-/,+5d' "$diradminb"/scripts/pi-hole/php/hea
 #sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/data.php
 #if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 1" && exit 1 ; fi
 
-sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$diradminb"/scripts/pi-hole/php/FTL.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 2" && exit 1 ; fi
+#sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$diradminb"/scripts/pi-hole/php/FTL.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 2" && exit 1 ; fi
 sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 3" && exit 1 ; fi
 sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
@@ -211,36 +211,36 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't di
 # -----------------
 
 # web admin footer update setup
-sed -i "s|https:\/\/github.com\/pi-hole\/pi-hole\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+sed -i "s|\$coreUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 1" && exit 1 ; fi
-sed -i "s|https:\/\/github.com\/pi-hole\/AdminLTE\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+sed -i "s|\$webUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 2" && exit 1 ; fi
-sed -i "s|https:\/\/github.com\/pi-hole\/FTL\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
+sed -i "s|\$ftlUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi
 
 # -----------------
 
 # sudo pihole full path (php-fpm compatibility)
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/api.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 1" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/header.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 2" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/groups.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 5" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/add.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 6" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 7" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/loginpage.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 8" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/teleporter.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 9" && exit 1 ; fi
-sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/customdns.php
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 9" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/api.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 1" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/header.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 2" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/groups.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 5" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/add.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 6" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 7" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/loginpage.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 8" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/teleporter.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 9" && exit 1 ; fi
+#sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/customdns.php
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 10" && exit 1 ; fi
 
 # -----------------
 
